languageCode = "zh-TW"
languageName = "中文"
weight = 1
title = "Tony 字傳"
contentDir = "content/zh-tw"

[params]
  displayName = "中文"
  isoCode = "zh-TW"
  dateFormat = "2006-01-02"
  description = "Tony 的技術部落格"

[params.author]
  name = "Tony"
  email = "blog@dexiang.me"
  headline = "Software Engineer"
  links = [
    { github = "https://github.com/dexiang" },
    { linkedin = "https://www.linkedin.com/in/tony-xu/" },
    { email = "mailto:tony@dexiang.me" },
  ]
