[zh-tw]
  title = "Tony 字傳"
  languageName = "中文"
  weight = 1
  languagedir = "ltr"
  #contentdir = "content/zh-tw"

[en-us]
  title = "Dexiang Blog"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  #contentdir = "content/en-us"

