[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "tech"
  name = "Technology"
  url = "technologies"
  weight = 2
    
[[main]]
  identifier = "trivia"
  name = "Trivia"
  url = "trivia"
  weight = 3

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 4