# -- Main Menu --

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Technology"
  pageRef = "technologies"
  weight = 20

[[main]]
  name = "Trivia"
  pageRef = "trivia"
  weight = 30

[[main]]
  name = "Archive"
  pageRef = "archive"
  weight = 40

[[main]]
  identifier = "search"
  pre = "search"
  weight = 99
